### ISSUE TITLE
Undefined variable

### ISSUE THREAD

**Issue by tomjn** [Automattic/VIP-Coding-Standards#91]
While scanning Ninja Forms 3.16 an issue arose as noted below:

```
PHP Notice:  Undefined variable: phpcsFile in /Users/tarendai/dev/git/VIP-Coding-Standards/WordPressVIPMinimum/Sniffs/Variables/VariableAnalysisSniff.php on line 1446
PHP Fatal error:  Uncaught Error: Call to a member function getTokens() on null in /Users/tarendai/dev/git/VIP-Coding-Standards/WordPressVIPMinimum/Sniffs/Variables/VariableAnalysisSniff.php:1446
Stack trace:
#0 [internal function]: WordPressVIPMinimum_Sniffs_Variables_VariableAnalysisSniff->filter_non_whitespace_tokens(1500)
#1 /Users/tarendai/dev/git/VIP-Coding-Standards/WordPressVIPMinimum/Sniffs/Variables/VariableAnalysisSniff.php(1320): array_filter(Array, Array)
#2 /Users/tarendai/dev/git/VIP-Coding-Standards/WordPressVIPMinimum/Sniffs/Variables/VariableAnalysisSniff.php(1381): WordPressVIPMinimum_Sniffs_Variables_VariableAnalysisSniff->processCompactArguments(Object(PHP_CodeSniffer_File), 1498, Array, 1251)
#3 /Users/tarendai/dev/git/VIP-Coding-Standards/WordPressVIPMinimum/Sniffs/Variables/VariableAnalysisSniff.php(359): WordPressVIPMinimum_Sniffs_Variables_VariableAnalysisSniff->processCompact(Object(PHP_CodeSniffer_File), 1498)
#4 /Users/tarendai/.composer/vendor/squizlabs/php_codesniffer/CodeSniffer/File.php(576): W in /Users/tarendai/dev/git/VIP-Coding-Standards/WordPressVIPMinimum/Sniffs/Variables/VariableAnalysisSniff.php on line 1446
```

Located at:

```
    function filter_non_whitespace_tokens($argumentPtr) {
        $tokens = $phpcsFile->getTokens();
        return $tokens[$argumentPtr]['code'] !== T_WHITESPACE;
    }
```

Traced back to https://github.com/Automattic/VIP-Coding-Standards/commit/fd3b20f52f6a4ff3d5f6263a5ad0d9ff3afab768

**Comment by david-binda** [comment]
Thanks for the report. This has been fixed in https://github.com/Automattic/VIP-Coding-Standards/pull/79
